# Site
title: "Bioinformatics Hub of Kenya initiative"
description: >
  Bridging the gap between well established bioinformaticians and aspiring ones through peer training and mentorship so as to enhance collaborations to foster quality scientific research and innovations and promote the sharing of data, skills and codes.
logo: ''
email: bioinformaticshubofkenya@gmail.com
repository: bioinformatics-hub-ke/BHKi.github.io
twitter: BioinfoHub_KE
gitter: 
url: https://bhki.org/
announcement_list: https://groups.google.com/forum/#!forum/ols-news
youtube: https://www.youtube.com/channel/UCWvCsVW7BF3Nml5VpLOdU5g/featured

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
  ols-1:
    permalink: /ols-1/:path/
    output: true
  ols-2:
    permalink: /ols-2/:path/
    output: true
  
includes_dir: .

plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
